baseURL = "http://example.org/"
languageCode = "en-us"
title = "Playing Rough Podcast"
theme = "pickles"
staticDir = "static"

# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright notice 2018"

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  patreon = "playingroughpodcast"
  twitter = "playing_rough"
  facebook = "PlayingRoughPodcast"
  instagram = "playing_rough"
  googleplus = "https://plus.google.com/u/0/113265228830148501574"
  tumblr = "playingroughpodcast"
  soundcloud = "2432511"
  youtube = "UCX3LPg-mE84Ew8wPJqXRe4Q"
  #author = "Your Name"
  #authorwebsite = "example.com"
  #avatar = "/path/to/avatar"
  #contact = "Your contact link (ex. mailto:foo@example.com)"
  #bio = "Your short bio"
  # Short subtitle/tagline. This is displayed in the header.
  #subtitle = "Short subtitle"
  # Logo image. This is displayed ogp image.
  logo_large = "/images/playing_rough_large.jpg"
  logo = "/images/playing_rough.jpg"
  favicon = "/images/playing_rough_icon.jpg"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
